### ISSUE TITLE
io_pwm liefert immer High-Signal

### ISSUE THREAD

**Issue by BjoernSch** [WLANThermo/WLANThermo_v2#1]
Am Ausgang für io_pwm steht ein ständiges High-Signal an, unabhängig vom Eingangswert.

**Comment by BjoernSch** [comment]
War ein Problem mit den Einstellungen.

**Comment by aschaefer85** [comment]
Muss gefixt werden. Auch wenn Duty Cycle 20% ist und man eine anstetuerung von 50% hat, darf das Ausgangssignal nicht ständig High-Signal ausgeben.

**Comment by BjoernSch** [comment]
Mir war nicht bewusst, das der Fehler noch vorhanden ist.
Berechnung ist korrigiert, sollte damit wirklich behoben sein.

**Comment by BjoernSch** [comment]
Getestet und behoben.
