### ISSUE TITLE
Fehler bei apt-get update

### ISSUE THREAD

**Issue by arminth** [WLANThermo/WLANThermo_v2#103]
2.8.0-beta5

apt-get update schmeißt eine Menge Fehler aus:

`Ign:1 http://packages.wlanthermo.com stretch InRelease
OK:2 http://raspbian.raspberrypi.org/raspbian stretch InRelease
OK:3 http://archive.raspberrypi.org/debian stretch InRelease
OK:4 http://packages.wlanthermo.com stretch-dev InRelease
Ign:5 http://packages.wlanthermo.com stretch Release
Ign:6 http://packages.wlanthermo.com stretch/main all Packages
Ign:7 http://packages.wlanthermo.com stretch/main armhf Packages
Ign:8 http://packages.wlanthermo.com stretch/main Translation-de
Ign:9 http://packages.wlanthermo.com stretch/main Translation-en
Ign:10 http://packages.wlanthermo.com stretch/main Translation-de_DE
Ign:6 http://packages.wlanthermo.com stretch/main all Packages
Ign:7 http://packages.wlanthermo.com stretch/main armhf Packages
Ign:8 http://packages.wlanthermo.com stretch/main Translation-de
Ign:9 http://packages.wlanthermo.com stretch/main Translation-en
Ign:10 http://packages.wlanthermo.com stretch/main Translation-de_DE
Ign:6 http://packages.wlanthermo.com stretch/main all Packages
Ign:7 http://packages.wlanthermo.com stretch/main armhf Packages
Ign:8 http://packages.wlanthermo.com stretch/main Translation-de
Ign:9 http://packages.wlanthermo.com stretch/main Translation-en
Ign:10 http://packages.wlanthermo.com stretch/main Translation-de_DE
Ign:6 http://packages.wlanthermo.com stretch/main all Packages
Ign:7 http://packages.wlanthermo.com stretch/main armhf Packages
Ign:8 http://packages.wlanthermo.com stretch/main Translation-de
Ign:9 http://packages.wlanthermo.com stretch/main Translation-en
Ign:10 http://packages.wlanthermo.com stretch/main Translation-de_DE
Ign:6 http://packages.wlanthermo.com stretch/main all Packages
Ign:7 http://packages.wlanthermo.com stretch/main armhf Packages
Ign:8 http://packages.wlanthermo.com stretch/main Translation-de
Ign:9 http://packages.wlanthermo.com stretch/main Translation-en
Ign:10 http://packages.wlanthermo.com stretch/main Translation-de_DE
Ign:6 http://packages.wlanthermo.com stretch/main all Packages
Fehl:7 http://packages.wlanthermo.com stretch/main armhf Packages
  404  Not Found
Ign:8 http://packages.wlanthermo.com stretch/main Translation-de
Ign:9 http://packages.wlanthermo.com stretch/main Translation-en
Ign:10 http://packages.wlanthermo.com stretch/main Translation-de_DE
Paketlisten werden gelesen... Fertig
W: The repository 'http://packages.wlanthermo.com stretch Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Fehlschlag beim Holen von http://packages.wlanthermo.com/dists/stretch/main/binary-armhf/Packages  404  Not Found
E: Einige Indexdateien konnten nicht heruntergeladen werden. Sie wurden ignoriert oder alte an ihrer Stelle benutzt.
`

**Comment by BjoernSch** [comment]
Das "stretch" Repository gibt es noch nicht auf dem Update Server, daher die Fehler.
