### ISSUE TITLE
LCD 204 shows garbage-characters after Version number

### ISSUE THREAD

**Issue by arminth** [WLANThermo/WLANThermo_v2#114]
As stated. The version shows with garbage added. Couldn't figure it out correctly. 
We need to change cut command line at least as follows
cat /var/www/header.php | grep '] = "V' | cut -c31-36

but still, there is a scrambled thing at the end (which could be the hex 0A character).

**Comment by BjoernSch** [comment]
Solved by d7da00295f9ec2f92234b03a52ed306cda0aa358
