### ISSUE TITLE
Alarmgrenzenänderung am lokalen Display wirken sich nicht auf eine laufende GUI aus

### ISSUE THREAD

**Issue by arminth** [WLANThermo/WLANThermo_v2#2]
Wenn man am Nextion die Alarmtemperatur ändert und parallel ein Web-GUI offen hat, datet sich diese GUI nicht auf und zeigt ggf. falsche Alarme an. Ein reload der Seite behebt das Problem. Nimmt man anstelle des Nextion ein weiteres GUI auf einem anderen Gerät, wird am ersten Gerät richtig aufdatiert.

**Comment by BjoernSch** [comment]
Flag file wird erzeugt
