### ISSUE TITLE
Websound-Alarm geht nicht

### ISSUE THREAD

**Issue by arminth** [WLANThermo/WLANThermo_v2#3]
Der Web-Sound-Alarm bei Android Chrome und Iphone Safari klingelt nicht mehr! Es wird Alarm angezeigt (rot), es erscheint ein Lautsprechersymbol, was man quittieren kann,  aber es kommt kein Sound.

**Comment by Phantomias2006** [comment]
Ich werde mir dieses Problem nochmal ansehen. Ich befürchte aber dass es keine Möglichkeit mehr gibt
einen automatischen Sound auf Mobile Devices abzuspielen. Deswegen gehen wir den weg eines HybridApp's.

**Comment by BjoernSch** [comment]
Keine Möglichkeit das zu ändern.
Web Push Notifications wären vielleicht ein Thema.
Designentscheidung für V3
