### ISSUE TITLE
IO / Lüfteranschluss

### ISSUE THREAD

**Issue by grilljunk** [WLANThermo/WLANThermo_v2#44]
da man ja 8 messfühler anschließen kann, könnte man ja locker 2 grills mit 4 Pulled Pork überwachen => gibt es eine möglichkeit 2 IO bzw. 2 lüfter anzuschließen um die beiden Grills unabhängig voneinander regeln zu können?

**Comment by BjoernSch** [comment]
Nein, bisher nicht.
