### ISSUE TITLE
Ramverbrauch im Display durch Variablen

### ISSUE THREAD

**Issue by BjoernSch** [WLANThermo/WLANThermo_v2#5]
Wir müssen mal über alle Variablen drüber gehen die eine txt Endung haben.
Die hauen so richtig in den RAM rein.
Aktuell sind die meisten auf 30 Zeichen begrenzt.
Wenn ich die aber auf 10 Zeichen limitiere fällt der RAM Bedarf drastisch.
An sich ja eine tolle Erkenntnis nur wenn der PI mal 11+ Zeichen sendet wird das komplett verworfen.
Das bedeutet das @BjoernSch die Zeichen erst in der py begrenzen muss.

Ganz genau das ich übrigens der Fehler den wir mal hatten. Den RAM Bedarf haben wir nie betrachtet.

**Comment by aschaefer85** [comment]
Variablentabelle angepasst.
HMI Änderungen folgen.

[WLAN Thermometer Variablentabelle.xlsx](https://github.com/WLANThermo/WLANThermo_v2/files/126651/WLAN.Thermometer.Variablentabelle.xlsx)

**Comment by aschaefer85** [comment]
In der Variablentabelle fehlende Variablen ergänzt 
Alte und schon gelöschte Variablen in der Variablentabelle gelöscht
HMI gemäss Variablentabelle angepasst.
Florians Namen auf der Info Seite korrigiert 

RAM verbrauch ist durch diese Änderungen um 50% gesunken
Alle Dateien bitte prüfen und hier auf GIT einsortieren (hab immer noch nicht ganz verstanden wie es geht :-( 

[20150211 Nextion 2,8 v0.7.zip](https://github.com/WLANThermo/WLANThermo_v2/files/127051/20150211.Nextion.2.8.v0.7.zip)

**Comment by BjoernSch** [comment]
Skript angepasst, aktuelle HMI hochgeladen.
