### ISSUE TITLE
K-Sensoren von der Add-On-Platine werden falsch angezeigt

### ISSUE THREAD

**Issue by arminth** [WLANThermo/WLANThermo_v2#63]
In der GUI und auch im Display werden die Werte von der Add-On-Platine als Maverick angezeigt.

**Comment by arminth** [comment]
Ergänzung: Es werden die werte in Kanal 8 und 9 angezeigt und nicht in 10 und 11.

**Comment by BjoernSch** [comment]
Muss man "nur" umbenennen. Maverick bleiben immer "die letzten", da diese bei fester Hardware an-/ abschaltbar sind. Kanalname ist ja eh konfigurierbar.
