### ISSUE TITLE
Falscher Sollwert bei Pitmaster 2 

### ISSUE THREAD

**Issue by arminth** [WLANThermo/WLANThermo_v2#65]
Wenn ich den zweiten Pitmaster auf den K-Sensor (jetzt ja Maverick1) stelle, erscheint trotz eingestelltem Sollwert von 110° ein Sollwert von 0° im Display.

**Comment by arminth** [comment]
Nach einem Reboot behoben.

**Comment by BjoernSch** [comment]
Nach einem Reboot behoben.
