### ISSUE TITLE
Fehlende Kanäle 

### ISSUE THREAD

**Issue by tealc** [WLANThermo/WLANThermo_v2#76]
Ein Problem mit dem Mini v2 Image:

Wenn als Startseite "Temperatur" gewählt ist, fehlen die Typ-K Kanäle. Geht man dann in das Menu und dann wieder auf Temperatur werden die zwei Kanäle angezeigt.

**Comment by BjoernSch** [comment]
Wurde  in  4bd6828 behoben.
