### ISSUE TITLE
Enable compression on lighttpd and php

### ISSUE THREAD

**Issue by designer2k2** [WLANThermo/WLANThermo_v2#82]
um Bandbreite zu sparen sollte beim lighttpd/php die compression aktiviert werden.
Damit schrumpft zb die Startseite von 4kb auf 1kb, und diese wird per Ajax ja ständig übertragen.
(die conf.php geht von 96kb auf 8kb runter)

ich hab dazu in der folgendes verändert php.ini:
zlib.output_compression = On
zlib.output_handler = On

hab aber keine Ahnung wie ich das hier eintragen kann...

**Comment by BjoernSch** [comment]
Da es keine großen Weiterentwicklungen in Version 2 gibt würde ich das gerne nicht mehr ändern.
Ich glaube es sollte keine negativen Auswirkungen haben da wir keine Seiten langsam und Stück für Stück aufbauen, aber 100% sicher bin ich mir nicht.
Für die nächste Version schreibe ich mir das auf den Zettel.
