### ISSUE TITLE
Extend information about pitmaster in app.php

### ISSUE THREAD

**Issue by designer2k2** [WLANThermo/WLANThermo_v2#87]
Hallo,

ich würde aus der app.php gerne noch folgende Werte über den Pitmaster bekommen:

- Channel where it regulates from **pit_ch**
- PID active **pit_controller_type**
- Open Lid detection active **pit_open_lid_detection**

Habe mich durch den Code gelesen, aber finde die Stelle nicht wo ich ansetzen muss um die $_SESSION["pitmaster"] um diese Werte zu ergänzen (sie stehen ja in der WLANThermo.conf)

Kann mir jemand einen Hinweis geben wo anzusetzen ist?

**Comment by BjoernSch** [comment]
In die Session wird es im Bereich:
https://github.com/WLANThermo/WLANThermo_v2/blob/13bfb94ff20c47c6410ee3d4cb84b2cd4351572c/software/var/www/function.php#L217
geladen.

> Open Lid detection active **pit_open_lid_detection**

Wofür? Finde ich relativ wenig spannend.

**Comment by designer2k2** [comment]
Danke für den Hinweis, PR gestellt!

Ja die open_lid_detection ist am wenigsten interessant davon, aber für die Visualisierung dennoch nützlich.

**Comment by BjoernSch** [comment]
Resolved by a6737b1e6909305bdb33b6cb941d5be2fe649a7c
